### ISSUE TITLE
Parser Date Error

### ISSUE THREAD

**Issue by chris-clm09** [byu-osl/citizen-budget#1]
Cedar Hills Parser data error:
- The Dates need to be in the format of MM/DD/YYYY not DD/MM/YYYY.

**Comment by dallinls** [comment]
Cool. Thanks

On Mon, Feb 25, 2013 at 10:08 PM, Chris notifications@github.com wrote:

> Cedar Hills Parser data error:
> - The Dates need to be in the format of MM/DD/YYYY not DD/MM/YYYY.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/byu-osl/citizen-budget/issues/1
> .

## 

Dallin L. Smith

**Comment by chris-clm09** [comment]
The parser has been update and the date issue fixed.
